service: cowsayify

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512
  region: us-east-1

plugins:
  - serverless-nextjs-plugin

custom:
  serverless-nextjs:
    nextConfigDir: './'
    pageConfig:
      cowsaid:
        events:
          - http:
              path: cowsaid/{key}
              request:
                parameters:
                  paths:
                    key: true
package:
  exclude:
    - ./**
